backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Emergency Messages"
    name: "messages"
    extension: json
    format: json
    create: false # Only 1 message at a time plz
    files:
      - label: "Website Emergency Message (Portal Message)"
        name: "message"
        file: "src/_data/messages.yaml"
        fields:
          - label: "Message (nl-NL)"
            name: message_nlnl
            required: false
            widget: markdown
            minimal: true
            buttons: [bold, italic, link]
            sanitize_preview: true
            modes: [raw, rich_text]
          - label: "Message (nl-BE)"
            name: message_nlbe
            required: false
            widget: markdown
            minimal: true
            buttons: [bold, italic, link]
            sanitize_preview: true
            modes: [raw, rich_text]
          - label: "Message (fr-BE)"
            name: message_frbe
            required: false
            widget: markdown
            minimal: true
            buttons: [bold, italic, link]
            sanitize_preview: true
            modes: [raw, rich_text]
